version: '3'
services:
  kali:
    build:
      dockerfile: ./Dockerfile
      target: dev
      context: .
    environment:
      - BINARY_EDGE_TOKEN=${BINARY_EDGE_TOKEN}
      - SECURITY_TRAILS_TOKEN=${SECURITY_TRAILS_TOKEN}
